### ISSUE TITLE
Fail to send MOBs to an address by mobcli

### ISSUE THREAD

**Issue by bafu** [mobilecoinofficial/full-service#154]
`mobcli` fails to send MOBs to an address.

Related issue: https://github.com/christian-oudard/mobilecoin-python-cli/issues/3

**Steps to Reproduce**

1. Follow the [MobileCoin CLI instructions](https://github.com/mobilecoinofficial/full-service/tree/develop/cli)
2. After the environment is set, run the command

        $ mobcli send f259df 0.01 3ZvFiT6ud8Y33Cm9QRWdC8V8Lu5ea9RZwTdtABWNmrU8aPAs5k7CS46ejroJLDCHZhuUX5uq4CpQR5VYGC3HRvPRDFAbbXFxUPTCS1JpVghaH5uZvGY4NZdfPadqFt5zNzXtP9g3C9o6pKGExsf6uxnbWiDqyH9QTQiBP5G2Xdp3K2ypTL52GZRc5eLeWVGAki1XSc6VDSxGrgvCst624sVXqfWvepK7Ud95anGNjdgv61BXgq

**Error Logs**

Check balances:

```
(venv) bafu@de-lab-cafe:~/codes/mobilecoin$ mobcli list

492ded 
  address 3wubViJ9tMBR9VQ2cVnecrfmSBH3Ub2WxNDByPnBD9ZuPcq5ovK5ohnBTAkXaxDivftSKpK4HZjcK63jfJZaABBfhqWdKzUQTZQdbRUSawY
  0.0000 MOB (synced) 

f259df 
  address 48cfuaeDwGCFbqnxRaPUwhxePdL7ZQf8zzW3Z57oorky4jY78N4Akw9jtEdnj2Fn8DqFFw7o9LzzgHoNzULEsyUoWws5frbBxuJe4ZQVwH1
  18.8600 MOB (synced) 
```

Send MOBs to an address on Testnet:

```
(venv) bafu@de-lab-cafe:~/codes/mobilecoin$ mobcli send f259df 0.01 3ZvFiT6ud8Y33Cm9QRWdC8V8Lu5ea9RZwTdtABWNmrU8aPAs5k7CS46ejroJLDCHZhuUX5uq4CpQR5VYGC3HRvPRDFAbbXFxUPTCS1JpVghaH5uZvGY4NZdfPadqFt5zNzXtP9g3C9o6pKGExsf6uxnbWiDqyH9QTQiBP5G2Xdp3K2ypTL52GZRc5eLeWVGAki1XSc6VDSxGrgvCst624sVXqfWvepK7Ud95anGNjdgv61BXgq
Traceback (most recent call last):
  File "/home/bafu/codes/mobilecoin/full-service/cli/mobilecoin/client.py", line 49, in _req
    response_data = r.json()
  File "/home/bafu/codes/mobilecoin/venv/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bafu/codes/mobilecoin/venv/bin/mobcli", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bafu/codes/mobilecoin/full-service/cli/bin/mobcli", line 3, in <module>
    CommandLineInterface().main()
  File "/home/bafu/codes/mobilecoin/full-service/cli/mobilecoin/cli.py", line 45, in main
    command_func(**args)
  File "/home/bafu/codes/mobilecoin/full-service/cli/mobilecoin/cli.py", line 423, in send
    network_status = self.client.get_network_status()
  File "/home/bafu/codes/mobilecoin/full-service/cli/mobilecoin/client.py", line 167, in get_network_status
    r = self._req({
  File "/home/bafu/codes/mobilecoin/full-service/cli/mobilecoin/client.py", line 51, in _req
    raise ValueError('API returned invalid JSON:', r.text)
ValueError: ('API returned invalid JSON:', 'Could not get value Error("unknown variant `get_network_status`, expected one of `create_account`, `import_account`, `import_account_from_legacy_root_entropy`, `export_account_secrets`, `get_all_accounts`, `get_account`, `update_account_name`, `remove_account`, `get_balance_for_account`, `build_and_submit_transaction`, `build_transaction`, `submit_transaction`, `get_all_transaction_logs_for_account`, `get_transaction_log`, `get_all_transaction_logs_for_block`, `get_all_transaction_logs_ordered_by_block`, `get_wallet_status`, `get_account_status`, `assign_address_for_account`, `get_all_addresses_for_account`, `verify_address`, `get_balance_for_address`, `get_all_txos_for_account`, `get_txo`, `get_all_txos_for_address`, `get_confirmations`, `validate_confirmation`, `get_mc_protocol_transaction`, `get_mc_protocol_txo`, `get_block`, `check_receiver_receipt_status`, `create_receiver_receipts`, `build_gift_code`, `submit_gift_code`, `get_gift_code`, `get_all_gift_codes`, `check_gift_code_status`, `claim_gift_code`, `remove_gift_code`", line: 0, column: 0)')
```

**Environment**

* `mobcli`: [commit `21dca63`](https://github.com/mobilecoinofficial/full-service/commit/21dca6374ee7097585f53368e26b3de6229e589b) (current `develop` branch)
* `full-service`: [`v1.0.0-pre.4` for Testnet](https://github.com/mobilecoinofficial/full-service/releases)
* OS: Ubuntu 20.04

**Comment by BrianCorbin** [comment]
Will look in to this ASAP! :) Thanks for brining this to our attention.

**Comment by bafu** [comment]
@BrianCorbin No problem :slightly_smiling_face: 

It seems to be a compatibility issue, and Henry@MobileCoin suggest me to use `v1.0.0-pre.5` which might fix this issue.

My working environment is Ubuntu, but the Linux Ubuntu binaries are not in the [`v1.0.0-pre.5` release note](https://github.com/mobilecoinofficial/full-service/releases/tag/v1.0.0-pre.5) (Ubuntu binaries are available in the prior releases.) Is there a plan to release Ubuntu binaries for `v1.0.0-pre.5`?

Thanks in advance!

**Comment by BrianCorbin** [comment]
I've updated the pre-release to include linux binaries! Let me know if this solves your issue :)

**Comment by bafu** [comment]
Upgrading `full-service` to `v1.0.0-pre.5` can resolve this issue, thanks Brian!

```
(venv) bafu@de-lab-cafe:~/codes/mobilecoin$ mobcli send 492ded 0.0006 48cfuaeDwGCFbqnxRaPUwhxePdL7ZQf8zzW3Z57oorky4jY78N4Akw9jtEdnj2Fn8DqFFw7o9LzzgHoNzULEsyUoWws5frbBxuJe4ZQVwH1
Sending 0.0006 MOB from account 492ded 
to address 48cfuaeDwGCFbqnxRaPUwhxePdL7ZQf8zzW3Z57oorky4jY78N4Akw9jtEdnj2Fn8DqFFw7o9LzzgHoNzULEsyUoWws5frbBxuJe4ZQVwH1
Fee is 0.0004 MOB, for a total amount of 0.0010 MOB.
Confirm? (Y/N) Y
Sent 0.0006 MOB, with a transaction fee of 0.0004 MOB
```
